### ISSUE TITLE
Improve Text Readability and Spacing in UI

### ISSUE THREAD

**Issue by cklose2000** [cklose2000/resumechat-simple#3]
## Problem
Customer feedback: "Text is too crunched, hard to read. Can we change the font/spacing?"

Based on code review, the formatted candidate listings use strict indentation patterns that may appear cramped:
```
1. John Smith
   Senior Developer
   Skills: React, Python, AWS

2. Jane Doe
   HR Manager
   Skills: Recruiting, Benefits, HRIS
```

### 1. Update Formatting in LLM Prompts
Modify the formatting instructions in `lib/llm_conversational.py` to add more breathing room:

```python
# Current format (cramped):
1. [Name]
   [Title]
   Skills: [list]

# Proposed format (spacious):
1. [Name]
   [Title]
   
   Skills: [list]
   ________________

2. [Name]
   [Title]
   
   Skills: [list]
   ________________
```

### 2. Update System Prompts
Change formatting instructions in both `lib/llm.py` and `lib/llm_conversational.py`:

```python
FORMATTING_RULES = """
When listing candidates, use this readable format:

1. **[Candidate Name]**
   *[Title/Role]*
   
   **Skills:** [comma-separated list]
   ________________________________

2. **[Next Candidate Name]**
   *[Title/Role]*
   
   **Skills:** [comma-separated list]
   ________________________________

RULES:
- Use bold for names (**Name**)
- Use italics for titles (*Title*)
- Add blank line after title
- Add separator line between candidates
- Maintain clear visual hierarchy
"""
```

### 3. Frontend CSS Updates
Update styles in the chat interfaces (`static/chat.html`, `static/test.html`):

```css
/* Improve typography */
.message-content {
    font-size: 16px;  /* Increase from 14px */
    line-height: 1.8; /* Increase from 1.5 */
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

/* Better spacing for candidate listings */
.message-content ol, .message-content ul {
    margin: 1.5em 0;
}

.message-content li {
    margin-bottom: 1.5em;
    padding-bottom: 1.5em;
    border-bottom: 1px solid #e0e0e0;
}

/* Improve code/formatted text */
.message-content pre {
    font-size: 14px;
    line-height: 1.6;
    padding: 1.5em;
    background: #f8f9fa;
    border-radius: 8px;
}
```

### 4. Alternative: Structured Display Mode
Add a toggle for "Compact" vs "Comfortable" view:

```javascript
// In chat.html
function toggleDisplayMode(mode) {
    if (mode === 'comfortable') {
        document.body.classList.add('comfortable-mode');
        // Larger fonts, more spacing
    } else {
        document.body.classList.remove('comfortable-mode');
        // Original compact view
    }
    localStorage.setItem('displayMode', mode);
}
```

### 5. Mobile Responsiveness
Ensure readability on mobile devices:

```css
@media (max-width: 768px) {
    .message-content {
        font-size: 18px;
        line-height: 2;
    }
    
    /* Reduce indentation on mobile */
    .message-content li {
        padding-left: 0.5em;
    }
}
```

## Testing Checklist
- [ ] Test readability on desktop (various screen sizes)
- [ ] Test readability on mobile devices
- [ ] Verify formatting consistency across all response types
- [ ] Check dark mode compatibility (if implemented)
- [ ] Ensure print styles are readable

## Benefits
- Improved user experience and readability
- Better accessibility for users with visual impairments
- Professional appearance
- Reduced eye strain during extended use
